//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLCitas.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisement
    {
        public System.Guid uId { get; set; }
        public string name { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<System.Guid> office_uId { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    
        public virtual Adverstisement_Status Adverstisement_Status { get; set; }
        public virtual Offices Offices { get; set; }
    }
}
