//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLCitas.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Citas()
        {
            this.Citas_Attachments = new HashSet<Citas_Attachments>();
            this.Servicios = new HashSet<Servicios>();
            this.Medicine_citas = new HashSet<Medicine_citas>();
        }
    
        public System.Guid uId { get; set; }
        public Nullable<System.Guid> consultory_uId { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> cita_date { get; set; }
        public Nullable<int> status_id { get; set; }
        public string Code { get; set; }
        public string title { get; set; }
        public string telefono { get; set; }
        public string razon { get; set; }
        public Nullable<decimal> precio { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> id_paciente { get; set; }
        public string observaciones_asistente { get; set; }
        public Nullable<double> peso { get; set; }
        public Nullable<double> temperatura { get; set; }
        public string presion { get; set; }
        public string receta { get; set; }
        public Nullable<System.DateTime> cancel_date { get; set; }
        public Nullable<System.DateTime> complete_date { get; set; }
        public Nullable<System.DateTime> confirm_date { get; set; }
        public Nullable<System.Guid> doctor_uid { get; set; }
        public Nullable<double> altura { get; set; }
        public string observacion_doctor { get; set; }
        public Nullable<double> glucosa { get; set; }
        public string motivo { get; set; }
        public string diagnostico { get; set; }
        public string ritmo_cardiaco { get; set; }
    
        public virtual Consultory Consultory { get; set; }
        public virtual Users Users { get; set; }
        public virtual Paciente Paciente { get; set; }
        public virtual Status_Citas Status_Citas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Citas_Attachments> Citas_Attachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicios> Servicios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medicine_citas> Medicine_citas { get; set; }
    }
}
