//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLCitas.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consultory()
        {
            this.Citas = new HashSet<Citas>();
            this.Users = new HashSet<Users>();
        }
    
        public System.Guid uId { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<System.Guid> office_uId { get; set; }
        public string alias { get; set; }
        public Nullable<int> status_id { get; set; }
        public string image_url { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string serie { get; set; }
        public Nullable<bool> allow_citas { get; set; }
        public Nullable<bool> allow_turn { get; set; }
        public Nullable<int> time_prom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Citas> Citas { get; set; }
        public virtual Offices Offices { get; set; }
        public virtual Consultory_Status Consultory_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users> Users { get; set; }
    }
}
