//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLCitas.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor_Configs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor_Configs()
        {
            this.Users = new HashSet<Users>();
            this.Councils__Medical_Specialties = new HashSet<Councils__Medical_Specialties>();
            this.Specialties = new HashSet<Specialties>();
        }
    
        public int id { get; set; }
        public string professional_license { get; set; }
        public string resume { get; set; }
        public string job_description { get; set; }
        public Nullable<int> logo1 { get; set; }
        public Nullable<int> logo2 { get; set; }
        public Nullable<int> logo3 { get; set; }
        public Nullable<int> logo4 { get; set; }
        public string facebook { get; set; }
        public string twitter { get; set; }
        public string instagram { get; set; }
        public string webpage { get; set; }
        public bool has_attachements { get; set; }
    
        public virtual Image Image { get; set; }
        public virtual Image Image1 { get; set; }
        public virtual Image Image2 { get; set; }
        public virtual Image Image3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users> Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Councils__Medical_Specialties> Councils__Medical_Specialties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Specialties> Specialties { get; set; }
    }
}
