//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLCitas.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine_citas
    {
        public int id { get; set; }
        public System.Guid cita_uId { get; set; }
        public Nullable<int> medicine_id { get; set; }
        public string dose { get; set; }
        public string frequency { get; set; }
        public string duration { get; set; }
        public string extra { get; set; }
        public string sentence { get; set; }
        public string medicine { get; set; }
    
        public virtual Citas Citas { get; set; }
    }
}
