//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLCitas.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Offices()
        {
            this.Advertisement = new HashSet<Advertisement>();
            this.Consultory = new HashSet<Consultory>();
            this.Offices_Users = new HashSet<Offices_Users>();
            this.Schedule = new HashSet<Schedule>();
        }
    
        public System.Guid uId { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<System.Guid> customer_uId { get; set; }
        public string image_url { get; set; }
        public string alias { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
        public int configuration_id { get; set; }
        public string phone { get; set; }
        public string phone_2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Advertisement> Advertisement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consultory> Consultory { get; set; }
        public virtual Customers Customers { get; set; }
        public virtual Offices_Configuration Offices_Configuration { get; set; }
        public virtual Offices_Status Offices_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Offices_Users> Offices_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedule { get; set; }
    }
}
