//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLCitas.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offices_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Offices_Users()
        {
            this.Schedule = new HashSet<Schedule>();
            this.Roles = new HashSet<Roles>();
        }
    
        public Nullable<System.Guid> office_uid { get; set; }
        public Nullable<System.Guid> user_uid { get; set; }
        public int prescription_id { get; set; }
        public Nullable<int> medical_appointment_duration { get; set; }
        public System.Guid uid { get; set; }
        public decimal price_per_appoinment { get; set; }
    
        public virtual Offices Offices { get; set; }
        public virtual Prescriptions Prescriptions { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Roles> Roles { get; set; }
    }
}
