//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLCitas.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paciente()
        {
            this.Citas = new HashSet<Citas>();
            this.Patient_Prescriptions = new HashSet<Patient_Prescriptions>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public string telefono { get; set; }
        public string curp { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public string alergias { get; set; }
        public string cirugias { get; set; }
        public string email { get; set; }
        public Nullable<int> sex_id { get; set; }
        public string heredofamiliares { get; set; }
        public string antecedentes_patologicos { get; set; }
        public string antecedentes_no_patologicos { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Citas> Citas { get; set; }
        public virtual Sex Sex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient_Prescriptions> Patient_Prescriptions { get; set; }
    }
}
