//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLCitas.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Prescriptions
    {
        public System.Guid uid { get; set; }
        public Nullable<int> patient_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string description { get; set; }
        public Nullable<System.Guid> user_uid { get; set; }
    
        public virtual Paciente Paciente { get; set; }
        public virtual Users Users { get; set; }
    }
}
