//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLCitas.DataLayer {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VLCitas.DataLayer.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerca de ti.
        /// </summary>
        public static string AboutYou {
            get {
                return ResourceManager.GetString("AboutYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aquí está tu información personal y de contacto.
        /// </summary>
        public static string AboutYouHelp {
            get {
                return ResourceManager.GetString("AboutYouHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tienes acceso a los siguientes lugares, por favor selecciona uno.
        /// </summary>
        public static string AccessTo {
            get {
                return ResourceManager.GetString("AccessTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acción.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activo.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Cita.
        /// </summary>
        public static string AddAppointment {
            get {
                return ResourceManager.GetString("AddAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar medicamento.
        /// </summary>
        public static string AddMedicine {
            get {
                return ResourceManager.GetString("AddMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar nueva cita.
        /// </summary>
        public static string AddNewDate {
            get {
                return ResourceManager.GetString("AddNewDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar nuevo paciente.
        /// </summary>
        public static string AddNewPatient {
            get {
                return ResourceManager.GetString("AddNewPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a + Agregar Especialidad.
        /// </summary>
        public static string AddSpeciality {
            get {
                return ResourceManager.GetString("AddSpeciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edad.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alergias.
        /// </summary>
        public static string Allergies {
            get {
                return ResourceManager.GetString("Allergies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alergia.
        /// </summary>
        public static string Allergy {
            get {
                return ResourceManager.GetString("Allergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos los usuarios.
        /// </summary>
        public static string AllUsers {
            get {
                return ResourceManager.GetString("AllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicados.
        /// </summary>
        public static string Applied {
            get {
                return ResourceManager.GetString("Applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicar.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema de Citas Medicas.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Citas Hoy.
        /// </summary>
        public static string AppoinmentsToday {
            get {
                return ResourceManager.GetString("AppoinmentsToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cita.
        /// </summary>
        public static string Appointment {
            get {
                return ResourceManager.GetString("Appointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de la cita.
        /// </summary>
        public static string AppointmentDate {
            get {
                return ResourceManager.GetString("AppointmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles de la Cita.
        /// </summary>
        public static string AppointmentDetails {
            get {
                return ResourceManager.GetString("AppointmentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cita se ha agendado correctamente.
        /// </summary>
        public static string AppointmentHasBeenScheduled {
            get {
                return ResourceManager.GetString("AppointmentHasBeenScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Citas.
        /// </summary>
        public static string Appointments {
            get {
                return ResourceManager.GetString("Appointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Citas al mes.
        /// </summary>
        public static string AppointmentsMonth {
            get {
                return ResourceManager.GetString("AppointmentsMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones Asistente.
        /// </summary>
        public static string AssistantObservations {
            get {
                return ResourceManager.GetString("AssistantObservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asistentes.
        /// </summary>
        public static string Assistants {
            get {
                return ResourceManager.GetString("Assistants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivos adjuntos.
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atención.
        /// </summary>
        public static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disponibles.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Horarios disponibles.
        /// </summary>
        public static string AvailableSchedule {
            get {
                return ResourceManager.GetString("AvailableSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Biografía.
        /// </summary>
        public static string Bio {
            get {
                return ResourceManager.GetString("Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de nacimiento.
        /// </summary>
        public static string Birthdate {
            get {
                return ResourceManager.GetString("Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agenda.
        /// </summary>
        public static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calendario.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Cancela {
            get {
                return ResourceManager.GetString("Cancela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Canceladas.
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catálogos.
        /// </summary>
        public static string Catalogs {
            get {
                return ResourceManager.GetString("Catalogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cédula Profesional.
        /// </summary>
        public static string Cedula {
            get {
                return ResourceManager.GetString("Cedula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor elija un doctor.
        /// </summary>
        public static string ChooseADoctor {
            get {
                return ResourceManager.GetString("ChooseADoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor elija un consultorio.
        ///   Busca una cadena traducida similar a Por favor eliga un consultorio.
        /// </summary>
        public static string ChooseConsultory {
            get {
                return ResourceManager.GetString("ChooseConsultory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escoge un rango de fechas.
        /// </summary>
        public static string ChooseRangeDate {
            get {
                return ResourceManager.GetString("ChooseRangeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escoge un reporte.
        /// </summary>
        public static string ChooseReport {
            get {
                return ResourceManager.GetString("ChooseReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elige una especialidad.
        /// </summary>
        public static string ChooseSpeciality {
            get {
                return ResourceManager.GetString("ChooseSpeciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Citas por estatus.
        /// </summary>
        public static string CitasByStatus {
            get {
                return ResourceManager.GetString("CitasByStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total de citas este mes.
        /// </summary>
        public static string CitasMonth {
            get {
                return ResourceManager.GetString("CitasMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Citas para el día de hoy.
        /// </summary>
        public static string CitasToday {
            get {
                return ResourceManager.GetString("CitasToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clínica.
        /// </summary>
        public static string Clinic {
            get {
                return ResourceManager.GetString("Clinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones para el asistente.
        /// </summary>
        public static string CommentsAssistant {
            get {
                return ResourceManager.GetString("CommentsAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Completadas.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu configuración en.
        /// </summary>
        public static string ConfigAt {
            get {
                return ResourceManager.GetString("ConfigAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aquí se muestran las configuraciones que tienes esta clínica en particular.
        /// </summary>
        public static string ConfigAtHelp {
            get {
                return ResourceManager.GetString("ConfigAtHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmadas.
        /// </summary>
        public static string Confirmed {
            get {
                return ResourceManager.GetString("Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultorio.
        /// </summary>
        public static string ConsultingRoom {
            get {
                return ResourceManager.GetString("ConsultingRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultorios.
        /// </summary>
        public static string ConsultingRooms {
            get {
                return ResourceManager.GetString("ConsultingRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto y Biografía.
        /// </summary>
        public static string ContactBio {
            get {
                return ResourceManager.GetString("ContactBio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CURP.
        /// </summary>
        public static string CURP {
            get {
                return ResourceManager.GetString("CURP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El clima actual!.
        /// </summary>
        public static string CurrentWeather {
            get {
                return ResourceManager.GetString("CurrentWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personalizado.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de.
        /// </summary>
        public static string DataFrom {
            get {
                return ResourceManager.GetString("DataFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de nacimiento.
        /// </summary>
        public static string Dateofbirth {
            get {
                return ResourceManager.GetString("Dateofbirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte de citas.
        /// </summary>
        public static string DatesReport {
            get {
                return ResourceManager.GetString("DatesReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Día.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Días.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle de la cita.
        /// </summary>
        public static string DetailsAppointment {
            get {
                return ResourceManager.GetString("DetailsAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diagnóstico.
        /// </summary>
        public static string Diagnosis {
            get {
                return ResourceManager.GetString("Diagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distribución por día.
        /// </summary>
        public static string DistributionByDay {
            get {
                return ResourceManager.GetString("DistributionByDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Doctor.
        /// </summary>
        public static string Doctor {
            get {
                return ResourceManager.GetString("Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Doctores.
        /// </summary>
        public static string Doctors {
            get {
                return ResourceManager.GetString("Doctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dosis.
        /// </summary>
        public static string Dose {
            get {
                return ResourceManager.GetString("Dose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arrastra los archivos aquí para subirlos.
        /// </summary>
        public static string DropFilesHereToUpload {
            get {
                return ResourceManager.GetString("DropFilesHereToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Duración.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Durante.
        /// </summary>
        public static string During {
            get {
                return ResourceManager.GetString("During", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cada.
        /// </summary>
        public static string Each {
            get {
                return ResourceManager.GetString("Each", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Perfil.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Fin.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora Fin.
        /// </summary>
        public static string EndHour {
            get {
                return ResourceManager.GetString("EndHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese los siguientes datos.
        /// </summary>
        public static string EnterFollowingData {
            get {
                return ResourceManager.GetString("EnterFollowingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este campo es requerido.
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtrar por usuario.
        /// </summary>
        public static string FilterByUser {
            get {
                return ResourceManager.GetString("FilterByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizar.
        /// </summary>
        public static string Finalize {
            get {
                return ResourceManager.GetString("Finalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizar.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cita Finalizada.
        /// </summary>
        public static string FinishedAppointment {
            get {
                return ResourceManager.GetString("FinishedAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quincena.
        /// </summary>
        public static string Fortnight {
            get {
                return ResourceManager.GetString("Fortnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Frecuencia.
        /// </summary>
        public static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Viernes.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre completo.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información General.
        /// </summary>
        public static string GeneralInformation {
            get {
                return ResourceManager.GetString("GeneralInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar reporte.
        /// </summary>
        public static string GenerateReport {
            get {
                return ResourceManager.GetString("GenerateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Glucosa.
        /// </summary>
        public static string Glucose {
            get {
                return ResourceManager.GetString("Glucose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro de glucosa.
        /// </summary>
        public static string GlucoseTracking {
            get {
                return ResourceManager.GetString("GlucoseTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrar.
        /// </summary>
        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ritmo cardiaco.
        /// </summary>
        public static string HeartRate {
            get {
                return ResourceManager.GetString("HeartRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Altura.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayuda.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Antecedentes heredofamiliares.
        /// </summary>
        public static string HereditaryFamily {
            get {
                return ResourceManager.GetString("HereditaryFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Hora:minutos).
        /// </summary>
        public static string Hhmm {
            get {
                return ResourceManager.GetString("Hhmm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hospital.
        /// </summary>
        public static string Hospital {
            get {
                return ResourceManager.GetString("Hospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Índice de masa corporal.
        /// </summary>
        public static string IMC {
            get {
                return ResourceManager.GetString("IMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce información.
        /// </summary>
        public static string IntroduceInformation {
            get {
                return ResourceManager.GetString("IntroduceInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción del trabajo.
        /// </summary>
        public static string JobDescription {
            get {
                return ResourceManager.GetString("JobDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Últimos 30 días.
        /// </summary>
        public static string Last_30_Days {
            get {
                return ResourceManager.GetString("Last_30_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los últimos 7 días.
        /// </summary>
        public static string Last_7_Days {
            get {
                return ResourceManager.GetString("Last_7_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Últimas citas.
        /// </summary>
        public static string LastAppointments {
            get {
                return ResourceManager.GetString("LastAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El mes pasado.
        /// </summary>
        public static string LastMonth {
            get {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver lista de citas.
        /// </summary>
        public static string Listappointments {
            get {
                return ResourceManager.GetString("Listappointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicia Sesion.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrio un error, verifica tu usuario y/o contraseña.
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Electrónico.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar reporte.
        /// </summary>
        public static string MakeReport {
            get {
                return ResourceManager.GetString("MakeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hombre.
        /// </summary>
        public static string Man {
            get {
                return ResourceManager.GetString("Man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrar.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notas médicas.
        /// </summary>
        public static string MedicalNotes {
            get {
                return ResourceManager.GetString("MedicalNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expediente clínico.
        /// </summary>
        public static string MedicalRecord {
            get {
                return ResourceManager.GetString("MedicalRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medicamento.
        /// </summary>
        public static string Medicine {
            get {
                return ResourceManager.GetString("Medicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Hola {0}!. Se ha agendado una cita el día {1} en el consultorio {2}.
        /// </summary>
        public static string Message_AgendarCita {
            get {
                return ResourceManager.GetString("Message_AgendarCita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Hola {0}!. Se ha agendado una cita el día {1} en el consultorio {2}. Te solicitamos nos confirmes tu asistencia o en su caso la canceles en el siguiente link {3}. .
        /// </summary>
        public static string Message_AgendarYConfirmarCita {
            get {
                return ResourceManager.GetString("Message_AgendarYConfirmarCita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minutos.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lunes.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mes.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ganancia por mes.
        /// </summary>
        public static string MonthlyRevenue {
            get {
                return ResourceManager.GetString("MonthlyRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Más Acciones.
        /// </summary>
        public static string MoreActions {
            get {
                return ResourceManager.GetString("MoreActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi Calendario.
        /// </summary>
        public static string MyCalendar {
            get {
                return ResourceManager.GetString("MyCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis Citas.
        /// </summary>
        public static string MyCitas {
            get {
                return ResourceManager.GetString("MyCitas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi bandeja de entrada.
        /// </summary>
        public static string MyInbox {
            get {
                return ResourceManager.GetString("MyInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elige nueva fecha.
        /// </summary>
        public static string Newdate {
            get {
                return ResourceManager.GetString("Newdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Paciente.
        /// </summary>
        public static string NewPatient {
            get {
                return ResourceManager.GetString("NewPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se han encontrado citas previas.
        /// </summary>
        public static string NoAppointments {
            get {
                return ResourceManager.GetString("NoAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Antecedentes personales no patológicos.
        /// </summary>
        public static string NonPathological {
            get {
                return ResourceManager.GetString("NonPathological", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes clinica asignada consulta a tu administrador .
        /// </summary>
        public static string NoOfficeError {
            get {
                return ResourceManager.GetString("NoOfficeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ningún paciente seleccionado.
        /// </summary>
        public static string NoPatientSelected {
            get {
                return ResourceManager.GetString("NoPatientSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay pacientes en el sistema.
        /// </summary>
        public static string NoPatientsInTheSystem {
            get {
                return ResourceManager.GetString("NoPatientsInTheSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron citas anteriores.
        /// </summary>
        public static string Nopreviousappointmentsfound {
            get {
                return ResourceManager.GetString("Nopreviousappointmentsfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Normal.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notas.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obesidad.
        /// </summary>
        public static string Obesity {
            get {
                return ResourceManager.GetString("Obesity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones.
        /// </summary>
        public static string Observations {
            get {
                return ResourceManager.GetString("Observations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones al asistente.
        /// </summary>
        public static string ObservationsToAssistant {
            get {
                return ResourceManager.GetString("ObservationsToAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones al doctor.
        /// </summary>
        public static string ObservationsToDoctor {
            get {
                return ResourceManager.GetString("ObservationsToDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a O también.
        /// </summary>
        public static string OrAlso {
            get {
                return ResourceManager.GetString("OrAlso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sobrepeso.
        /// </summary>
        public static string Overweight {
            get {
                return ResourceManager.GetString("Overweight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Antecedentes personales patológicos.
        /// </summary>
        public static string PathologicalPersonal {
            get {
                return ResourceManager.GetString("PathologicalPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paciente.
        /// </summary>
        public static string Patient {
            get {
                return ResourceManager.GetString("Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos del Paciente.
        /// </summary>
        public static string PatientData {
            get {
                return ResourceManager.GetString("PatientData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe el paciente en el sistema.
        /// </summary>
        public static string PatientDoesNotExist {
            get {
                return ResourceManager.GetString("PatientDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información Personal.
        /// </summary>
        public static string PersonalInfo {
            get {
                return ResourceManager.GetString("PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor seleccione un paciente para la cita.
        /// </summary>
        public static string PleaseSelectAPatientForAppointment {
            get {
                return ResourceManager.GetString("PleaseSelectAPatientForAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor seleccione una fecha para la cita.
        /// </summary>
        public static string PleaseSelectDateForAppointment {
            get {
                return ResourceManager.GetString("PleaseSelectDateForAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Receta.
        /// </summary>
        public static string Prescription {
            get {
                return ResourceManager.GetString("Prescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recetas Médicas.
        /// </summary>
        public static string Prescriptions {
            get {
                return ResourceManager.GetString("Prescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presión.
        /// </summary>
        public static string Pressure {
            get {
                return ResourceManager.GetString("Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentarios previosa a la cita.
        /// </summary>
        public static string PreviousComments {
            get {
                return ResourceManager.GetString("PreviousComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa la fecha.
        /// </summary>
        public static string PutDate {
            get {
                return ResourceManager.GetString("PutDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Costo por consulta.
        /// </summary>
        public static string RateByDate {
            get {
                return ResourceManager.GetString("RateByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Razón.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Motivo de la consulta.
        /// </summary>
        public static string ReasonConsultation {
            get {
                return ResourceManager.GetString("ReasonConsultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pacientes recientes.
        /// </summary>
        public static string RecentPatients {
            get {
                return ResourceManager.GetString("RecentPatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expedientes.
        /// </summary>
        public static string Records {
            get {
                return ResourceManager.GetString("Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Filtro.
        /// </summary>
        public static string RemoveFilter {
            get {
                return ResourceManager.GetString("RemoveFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte creado correctamente desde el.
        /// </summary>
        public static string Report_created {
            get {
                return ResourceManager.GetString("Report_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportes.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportes por servicio.
        /// </summary>
        public static string ReportsByService {
            get {
                return ResourceManager.GetString("ReportsByService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resultados.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Currículum.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresos.
        /// </summary>
        public static string Revenue {
            get {
                return ResourceManager.GetString("Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingreso al Mes.
        /// </summary>
        public static string RevenueMonth {
            get {
                return ResourceManager.GetString("RevenueMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresos.
        /// </summary>
        public static string Revenues {
            get {
                return ResourceManager.GetString("Revenues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingreso Hoy.
        /// </summary>
        public static string RevenueToday {
            get {
                return ResourceManager.GetString("RevenueToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos los derechos reservados.
        /// </summary>
        public static string Rights {
            get {
                return ResourceManager.GetString("Rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rol.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sábado.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Horario.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agendadas.
        /// </summary>
        public static string Scheduled {
            get {
                return ResourceManager.GetString("Scheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resultados de la búsqueda.
        /// </summary>
        public static string SeacrhResults {
            get {
                return ResourceManager.GetString("SeacrhResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar Paciente.
        /// </summary>
        public static string SearchPatient {
            get {
                return ResourceManager.GetString("SearchPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar Paciente por Nombre, Tél, Correo o Curp.
        /// </summary>
        public static string SearchPatientByNamePhoneEmailOrID {
            get {
                return ResourceManager.GetString("SearchPatientByNamePhoneEmailOrID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar expediente.
        /// </summary>
        public static string SearchRecord {
            get {
                return ResourceManager.GetString("SearchRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Busca entre tus pacientes por nombre o número de celular.
        /// </summary>
        public static string SearchRecordHelp {
            get {
                return ResourceManager.GetString("SearchRecordHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver.
        /// </summary>
        public static string See {
            get {
                return ResourceManager.GetString("See", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Calendario.
        /// </summary>
        public static string SeeCalendar {
            get {
                return ResourceManager.GetString("SeeCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Lista.
        /// </summary>
        public static string SeeList {
            get {
                return ResourceManager.GetString("SeeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona un paciente.
        /// </summary>
        public static string SelectAPatient {
            get {
                return ResourceManager.GetString("SelectAPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona una fecha.
        /// </summary>
        public static string SelectDate {
            get {
                return ResourceManager.GetString("SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora seleccionada.
        /// </summary>
        public static string SelectedTime {
            get {
                return ResourceManager.GetString("SelectedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar usuario.
        /// </summary>
        public static string SelectUser {
            get {
                return ResourceManager.GetString("SelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione el perfil con el que desea trabajar.
        /// </summary>
        public static string SelectYourProfileToWork {
            get {
                return ResourceManager.GetString("SelectYourProfileToWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicios.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sexo.
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar reporte.
        /// </summary>
        public static string ShowReport {
            get {
                return ResourceManager.GetString("ShowReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Especialidades.
        /// </summary>
        public static string Specialities {
            get {
                return ResourceManager.GetString("Specialities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aquí puedes configurar tus especialidades.
        /// </summary>
        public static string SpecialitiesHelp {
            get {
                return ResourceManager.GetString("SpecialitiesHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Especialidad.
        /// </summary>
        public static string Speciality {
            get {
                return ResourceManager.GetString("Speciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Inicio.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora de Inicio.
        /// </summary>
        public static string StartHour {
            get {
                return ResourceManager.GetString("StartHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estadísticas.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estatus.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resumen.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Domingo.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cirugías.
        /// </summary>
        public static string Surgeries {
            get {
                return ResourceManager.GetString("Surgeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cirugía.
        /// </summary>
        public static string Surgery {
            get {
                return ResourceManager.GetString("Surgery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Temperatura (Cº).
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este mes.
        /// </summary>
        public static string ThisMonth {
            get {
                return ResourceManager.GetString("ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jueves.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo promedio de cita.
        /// </summary>
        public static string TimeByDate {
            get {
                return ResourceManager.GetString("TimeByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Titulo.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hasta.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hoy.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agendar.
        /// </summary>
        public static string ToSchedule {
            get {
                return ResourceManager.GetString("ToSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total de Citas.
        /// </summary>
        public static string TotalAppointments {
            get {
                return ResourceManager.GetString("TotalAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total de ingresos.
        /// </summary>
        public static string TotalRevenue {
            get {
                return ResourceManager.GetString("TotalRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Martes.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin atender.
        /// </summary>
        public static string UnAttended {
            get {
                return ResourceManager.GetString("UnAttended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bajo peso.
        /// </summary>
        public static string UnderWeight {
            get {
                return ResourceManager.GetString("UnderWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin atender.
        /// </summary>
        public static string Unnattended {
            get {
                return ResourceManager.GetString("Unnattended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hasta.
        /// </summary>
        public static string Until {
            get {
                return ResourceManager.GetString("Until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vacaciones.
        /// </summary>
        public static string Vacations {
            get {
                return ResourceManager.GetString("Vacations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo de vaciones o ausencia.
        /// </summary>
        public static string VacationTime {
            get {
                return ResourceManager.GetString("VacationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Signos Vitales.
        /// </summary>
        public static string VitalSigns {
            get {
                return ResourceManager.GetString("VitalSigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sitio Web.
        /// </summary>
        public static string WebSite {
            get {
                return ResourceManager.GetString("WebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Miércoles.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Peso (Kg).
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro de peso.
        /// </summary>
        public static string WeightTracking {
            get {
                return ResourceManager.GetString("WeightTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido a.
        /// </summary>
        public static string WelcomeTo {
            get {
                return ResourceManager.GetString("WelcomeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mujer.
        /// </summary>
        public static string Woman {
            get {
                return ResourceManager.GetString("Woman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trabajar como:.
        /// </summary>
        public static string WorkAs {
            get {
                return ResourceManager.GetString("WorkAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Días de trabajo.
        /// </summary>
        public static string WorkDays {
            get {
                return ResourceManager.GetString("WorkDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Año.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Años.
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayer.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Estos son el total de tus citas este mes!.
        /// </summary>
        public static string YourAppointmentForMonth {
            get {
                return ResourceManager.GetString("YourAppointmentForMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Estas son las citas programadas para el día de hoy!.
        /// </summary>
        public static string YourAppointmentForToday {
            get {
                return ResourceManager.GetString("YourAppointmentForToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu Calendario.
        /// </summary>
        public static string YourCalendar {
            get {
                return ResourceManager.GetString("YourCalendar", resourceCulture);
            }
        }
    }
}
