//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLCitas.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schedule()
        {
            this.Offices_Users = new HashSet<Offices_Users>();
        }
    
        public int id { get; set; }
        public Nullable<bool> lunes { get; set; }
        public Nullable<bool> martes { get; set; }
        public Nullable<bool> miercoles { get; set; }
        public Nullable<bool> jueves { get; set; }
        public Nullable<bool> viernes { get; set; }
        public Nullable<bool> sabado { get; set; }
        public Nullable<bool> domingo { get; set; }
        public Nullable<System.TimeSpan> start_hour { get; set; }
        public Nullable<System.TimeSpan> end_hour { get; set; }
        public Nullable<System.Guid> oficina_uId { get; set; }
        public Nullable<int> status { get; set; }
        public string schedule_name { get; set; }
    
        public virtual Offices Offices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Offices_Users> Offices_Users { get; set; }
    }
}
