//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLCitas.DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class VL_CitasEntities : DbContext
    {
        public VL_CitasEntities()
            : base("name=VL_CitasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adverstisement_Status> Adverstisement_Status { get; set; }
        public virtual DbSet<Advertisement> Advertisement { get; set; }
        public virtual DbSet<Citas> Citas { get; set; }
        public virtual DbSet<Citas_Attachments> Citas_Attachments { get; set; }
        public virtual DbSet<Configs_Images> Configs_Images { get; set; }
        public virtual DbSet<Consultory> Consultory { get; set; }
        public virtual DbSet<Consultory_Status> Consultory_Status { get; set; }
        public virtual DbSet<Councils__Medical_Specialties> Councils__Medical_Specialties { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Customers_Status> Customers_Status { get; set; }
        public virtual DbSet<Doctor_Configs> Doctor_Configs { get; set; }
        public virtual DbSet<Image> Image { get; set; }
        public virtual DbSet<Module> Module { get; set; }
        public virtual DbSet<Offices> Offices { get; set; }
        public virtual DbSet<Offices_Configuration> Offices_Configuration { get; set; }
        public virtual DbSet<Offices_Status> Offices_Status { get; set; }
        public virtual DbSet<Offices_Users> Offices_Users { get; set; }
        public virtual DbSet<Paciente> Paciente { get; set; }
        public virtual DbSet<Patient_Prescriptions> Patient_Prescriptions { get; set; }
        public virtual DbSet<Prescriptions> Prescriptions { get; set; }
        public virtual DbSet<Reports> Reports { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Roles_Status> Roles_Status { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<Servicios> Servicios { get; set; }
        public virtual DbSet<Sex> Sex { get; set; }
        public virtual DbSet<Specialties> Specialties { get; set; }
        public virtual DbSet<Status_Citas> Status_Citas { get; set; }
        public virtual DbSet<TimeZones> TimeZones { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Users_Status> Users_Status { get; set; }
        public virtual DbSet<Vacations> Vacations { get; set; }
        public virtual DbSet<Medicine_citas> Medicine_citas { get; set; }
    
        public virtual ObjectResult<Get_TotalCitasByStatusxConsultories_Result> Get_TotalCitasByStatusxConsultories(Nullable<System.Guid> off_uId)
        {
            var off_uIdParameter = off_uId.HasValue ?
                new ObjectParameter("off_uId", off_uId) :
                new ObjectParameter("off_uId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_TotalCitasByStatusxConsultories_Result>("Get_TotalCitasByStatusxConsultories", off_uIdParameter);
        }
    
        public virtual ObjectResult<GetCalendarCitas_Result> GetCalendarCitas(Nullable<System.Guid> office_uid)
        {
            var office_uidParameter = office_uid.HasValue ?
                new ObjectParameter("Office_uid", office_uid) :
                new ObjectParameter("Office_uid", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCalendarCitas_Result>("GetCalendarCitas", office_uidParameter);
        }
    
        public virtual ObjectResult<GetCitasByConsultory_Result> GetCitasByConsultory(Nullable<System.Guid> consultory_uId)
        {
            var consultory_uIdParameter = consultory_uId.HasValue ?
                new ObjectParameter("consultory_uId", consultory_uId) :
                new ObjectParameter("consultory_uId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCitasByConsultory_Result>("GetCitasByConsultory", consultory_uIdParameter);
        }
    
        public virtual ObjectResult<GetCitasByDoctor_Result> GetCitasByDoctor(Nullable<System.Guid> user_uId)
        {
            var user_uIdParameter = user_uId.HasValue ?
                new ObjectParameter("user_uId", user_uId) :
                new ObjectParameter("user_uId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCitasByDoctor_Result>("GetCitasByDoctor", user_uIdParameter);
        }
    
        public virtual ObjectResult<GetCitasByStatus_Result> GetCitasByStatus(Nullable<System.Guid> off_uId)
        {
            var off_uIdParameter = off_uId.HasValue ?
                new ObjectParameter("off_uId", off_uId) :
                new ObjectParameter("off_uId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCitasByStatus_Result>("GetCitasByStatus", off_uIdParameter);
        }
    
        public virtual ObjectResult<GetCitasByStatusByConsultory_Result> GetCitasByStatusByConsultory(Nullable<System.Guid> consultory_uId)
        {
            var consultory_uIdParameter = consultory_uId.HasValue ?
                new ObjectParameter("consultory_uId", consultory_uId) :
                new ObjectParameter("consultory_uId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCitasByStatusByConsultory_Result>("GetCitasByStatusByConsultory", consultory_uIdParameter);
        }
    
        public virtual ObjectResult<GetCountCitasByConsultory_Result> GetCountCitasByConsultory(Nullable<System.Guid> off_uId)
        {
            var off_uIdParameter = off_uId.HasValue ?
                new ObjectParameter("off_uId", off_uId) :
                new ObjectParameter("off_uId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCountCitasByConsultory_Result>("GetCountCitasByConsultory", off_uIdParameter);
        }
    
        public virtual ObjectResult<GetGananciaByMonth_Result> GetGananciaByMonth(Nullable<System.Guid> off_uId)
        {
            var off_uIdParameter = off_uId.HasValue ?
                new ObjectParameter("off_uId", off_uId) :
                new ObjectParameter("off_uId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetGananciaByMonth_Result>("GetGananciaByMonth", off_uIdParameter);
        }
    
        public virtual ObjectResult<GetGananciaByMonthByConsultory_Result> GetGananciaByMonthByConsultory(Nullable<System.Guid> dep_uId)
        {
            var dep_uIdParameter = dep_uId.HasValue ?
                new ObjectParameter("dep_uId", dep_uId) :
                new ObjectParameter("dep_uId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetGananciaByMonthByConsultory_Result>("GetGananciaByMonthByConsultory", dep_uIdParameter);
        }
    
        public virtual ObjectResult<GetInvoicesByOfficeConsultory_Result> GetInvoicesByOfficeConsultory(Nullable<System.Guid> off_uId)
        {
            var off_uIdParameter = off_uId.HasValue ?
                new ObjectParameter("off_uId", off_uId) :
                new ObjectParameter("off_uId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInvoicesByOfficeConsultory_Result>("GetInvoicesByOfficeConsultory", off_uIdParameter);
        }
    
        public virtual ObjectResult<GetInvoicesCitasByConsultory_Result> GetInvoicesCitasByConsultory(Nullable<System.Guid> consultory_uId)
        {
            var consultory_uIdParameter = consultory_uId.HasValue ?
                new ObjectParameter("consultory_uId", consultory_uId) :
                new ObjectParameter("consultory_uId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInvoicesCitasByConsultory_Result>("GetInvoicesCitasByConsultory", consultory_uIdParameter);
        }
    
        public virtual ObjectResult<GetLastCitas_Result> GetLastCitas(Nullable<System.Guid> consultory_uId)
        {
            var consultory_uIdParameter = consultory_uId.HasValue ?
                new ObjectParameter("consultory_uId", consultory_uId) :
                new ObjectParameter("consultory_uId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLastCitas_Result>("GetLastCitas", consultory_uIdParameter);
        }
    
        public virtual ObjectResult<GetMonthCitas_Result> GetMonthCitas(Nullable<System.Guid> off_uId)
        {
            var off_uIdParameter = off_uId.HasValue ?
                new ObjectParameter("off_uId", off_uId) :
                new ObjectParameter("off_uId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMonthCitas_Result>("GetMonthCitas", off_uIdParameter);
        }
    
        public virtual ObjectResult<GetMonthCitasByConsultory_Result> GetMonthCitasByConsultory(Nullable<System.Guid> consultory_uId)
        {
            var consultory_uIdParameter = consultory_uId.HasValue ?
                new ObjectParameter("consultory_uId", consultory_uId) :
                new ObjectParameter("consultory_uId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMonthCitasByConsultory_Result>("GetMonthCitasByConsultory", consultory_uIdParameter);
        }
    
        public virtual ObjectResult<GetScheduleByConsultory_Result> GetScheduleByConsultory(Nullable<System.Guid> consultory_uId, Nullable<System.Guid> office_uid)
        {
            var consultory_uIdParameter = consultory_uId.HasValue ?
                new ObjectParameter("consultory_uId", consultory_uId) :
                new ObjectParameter("consultory_uId", typeof(System.Guid));
    
            var office_uidParameter = office_uid.HasValue ?
                new ObjectParameter("office_uid", office_uid) :
                new ObjectParameter("office_uid", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetScheduleByConsultory_Result>("GetScheduleByConsultory", consultory_uIdParameter, office_uidParameter);
        }
    
        public virtual ObjectResult<GetScheduleByOfficeAndDoctor_Result> GetScheduleByOfficeAndDoctor(Nullable<System.Guid> user_uId)
        {
            var user_uIdParameter = user_uId.HasValue ?
                new ObjectParameter("user_uId", user_uId) :
                new ObjectParameter("user_uId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetScheduleByOfficeAndDoctor_Result>("GetScheduleByOfficeAndDoctor", user_uIdParameter);
        }
    
        public virtual ObjectResult<Reports_GetCitasByDays_Result> Reports_GetCitasByDays(Nullable<System.Guid> off_uId, Nullable<System.Guid> doctor_uId, Nullable<System.DateTime> start_date, Nullable<System.DateTime> end_date)
        {
            var off_uIdParameter = off_uId.HasValue ?
                new ObjectParameter("off_uId", off_uId) :
                new ObjectParameter("off_uId", typeof(System.Guid));
    
            var doctor_uIdParameter = doctor_uId.HasValue ?
                new ObjectParameter("doctor_uId", doctor_uId) :
                new ObjectParameter("doctor_uId", typeof(System.Guid));
    
            var start_dateParameter = start_date.HasValue ?
                new ObjectParameter("start_date", start_date) :
                new ObjectParameter("start_date", typeof(System.DateTime));
    
            var end_dateParameter = end_date.HasValue ?
                new ObjectParameter("end_date", end_date) :
                new ObjectParameter("end_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Reports_GetCitasByDays_Result>("Reports_GetCitasByDays", off_uIdParameter, doctor_uIdParameter, start_dateParameter, end_dateParameter);
        }
    
        public virtual ObjectResult<Reports_GetCitasByStatus_Result> Reports_GetCitasByStatus(Nullable<System.Guid> off_uId, Nullable<System.Guid> doctor_uId, Nullable<System.DateTime> start_date, Nullable<System.DateTime> end_date)
        {
            var off_uIdParameter = off_uId.HasValue ?
                new ObjectParameter("off_uId", off_uId) :
                new ObjectParameter("off_uId", typeof(System.Guid));
    
            var doctor_uIdParameter = doctor_uId.HasValue ?
                new ObjectParameter("doctor_uId", doctor_uId) :
                new ObjectParameter("doctor_uId", typeof(System.Guid));
    
            var start_dateParameter = start_date.HasValue ?
                new ObjectParameter("start_date", start_date) :
                new ObjectParameter("start_date", typeof(System.DateTime));
    
            var end_dateParameter = end_date.HasValue ?
                new ObjectParameter("end_date", end_date) :
                new ObjectParameter("end_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Reports_GetCitasByStatus_Result>("Reports_GetCitasByStatus", off_uIdParameter, doctor_uIdParameter, start_dateParameter, end_dateParameter);
        }
    
        public virtual ObjectResult<Reports_GetSummaryHeader_Result> Reports_GetSummaryHeader(Nullable<System.Guid> off_uId, Nullable<System.Guid> doctor_uId, Nullable<System.DateTime> start_date, Nullable<System.DateTime> end_date)
        {
            var off_uIdParameter = off_uId.HasValue ?
                new ObjectParameter("off_uId", off_uId) :
                new ObjectParameter("off_uId", typeof(System.Guid));
    
            var doctor_uIdParameter = doctor_uId.HasValue ?
                new ObjectParameter("doctor_uId", doctor_uId) :
                new ObjectParameter("doctor_uId", typeof(System.Guid));
    
            var start_dateParameter = start_date.HasValue ?
                new ObjectParameter("start_date", start_date) :
                new ObjectParameter("start_date", typeof(System.DateTime));
    
            var end_dateParameter = end_date.HasValue ?
                new ObjectParameter("end_date", end_date) :
                new ObjectParameter("end_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Reports_GetSummaryHeader_Result>("Reports_GetSummaryHeader", off_uIdParameter, doctor_uIdParameter, start_dateParameter, end_dateParameter);
        }
    
        public virtual ObjectResult<Reports_ServicesSummary_Result> Reports_ServicesSummary(Nullable<System.Guid> off_uId, Nullable<System.Guid> doctor_uId, Nullable<System.DateTime> start_date, Nullable<System.DateTime> end_date)
        {
            var off_uIdParameter = off_uId.HasValue ?
                new ObjectParameter("off_uId", off_uId) :
                new ObjectParameter("off_uId", typeof(System.Guid));
    
            var doctor_uIdParameter = doctor_uId.HasValue ?
                new ObjectParameter("doctor_uId", doctor_uId) :
                new ObjectParameter("doctor_uId", typeof(System.Guid));
    
            var start_dateParameter = start_date.HasValue ?
                new ObjectParameter("start_date", start_date) :
                new ObjectParameter("start_date", typeof(System.DateTime));
    
            var end_dateParameter = end_date.HasValue ?
                new ObjectParameter("end_date", end_date) :
                new ObjectParameter("end_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Reports_ServicesSummary_Result>("Reports_ServicesSummary", off_uIdParameter, doctor_uIdParameter, start_dateParameter, end_dateParameter);
        }
    
        public virtual ObjectResult<SP_Horario_By_Doctor_Office_Result> SP_Horario_By_Doctor_Office(Nullable<System.Guid> user_uId, Nullable<System.Guid> office_uId, Nullable<System.DateTime> fecha)
        {
            var user_uIdParameter = user_uId.HasValue ?
                new ObjectParameter("user_uId", user_uId) :
                new ObjectParameter("user_uId", typeof(System.Guid));
    
            var office_uIdParameter = office_uId.HasValue ?
                new ObjectParameter("office_uId", office_uId) :
                new ObjectParameter("office_uId", typeof(System.Guid));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Horario_By_Doctor_Office_Result>("SP_Horario_By_Doctor_Office", user_uIdParameter, office_uIdParameter, fechaParameter);
        }
    
        public virtual ObjectResult<SP_Horario_DisponibleByDoctor_Result> SP_Horario_DisponibleByDoctor(Nullable<System.Guid> offie_uId, Nullable<System.Guid> doctor_uId, Nullable<System.DateTime> fecha)
        {
            var offie_uIdParameter = offie_uId.HasValue ?
                new ObjectParameter("offie_uId", offie_uId) :
                new ObjectParameter("offie_uId", typeof(System.Guid));
    
            var doctor_uIdParameter = doctor_uId.HasValue ?
                new ObjectParameter("doctor_uId", doctor_uId) :
                new ObjectParameter("doctor_uId", typeof(System.Guid));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Horario_DisponibleByDoctor_Result>("SP_Horario_DisponibleByDoctor", offie_uIdParameter, doctor_uIdParameter, fechaParameter);
        }
    
        public virtual ObjectResult<SPE_GananciaByMonthConsultory_Result> SPE_GananciaByMonthConsultory(Nullable<System.Guid> con_uId)
        {
            var con_uIdParameter = con_uId.HasValue ?
                new ObjectParameter("con_uId", con_uId) :
                new ObjectParameter("con_uId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPE_GananciaByMonthConsultory_Result>("SPE_GananciaByMonthConsultory", con_uIdParameter);
        }
    
        public virtual ObjectResult<SPE_GananciaXMes_Result> SPE_GananciaXMes(Nullable<System.Guid> consultory_uId)
        {
            var consultory_uIdParameter = consultory_uId.HasValue ?
                new ObjectParameter("consultory_uId", consultory_uId) :
                new ObjectParameter("consultory_uId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPE_GananciaXMes_Result>("SPE_GananciaXMes", consultory_uIdParameter);
        }
    
        public virtual ObjectResult<SPE_LAST30DAYS_Result> SPE_LAST30DAYS(Nullable<System.Guid> consultory_uId)
        {
            var consultory_uIdParameter = consultory_uId.HasValue ?
                new ObjectParameter("consultory_uId", consultory_uId) :
                new ObjectParameter("consultory_uId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPE_LAST30DAYS_Result>("SPE_LAST30DAYS", consultory_uIdParameter);
        }
    
        public virtual ObjectResult<SPE_LASTSIXMONTHS_Result> SPE_LASTSIXMONTHS(Nullable<System.Guid> consultory_uId)
        {
            var consultory_uIdParameter = consultory_uId.HasValue ?
                new ObjectParameter("consultory_uId", consultory_uId) :
                new ObjectParameter("consultory_uId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPE_LASTSIXMONTHS_Result>("SPE_LASTSIXMONTHS", consultory_uIdParameter);
        }
    
        public virtual ObjectResult<SPR_Ganancia_Mes_Result> SPR_Ganancia_Mes(Nullable<System.Guid> consultory_uId, Nullable<System.DateTime> start, Nullable<System.DateTime> ended, Nullable<int> id_user)
        {
            var consultory_uIdParameter = consultory_uId.HasValue ?
                new ObjectParameter("consultory_uId", consultory_uId) :
                new ObjectParameter("consultory_uId", typeof(System.Guid));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endedParameter = ended.HasValue ?
                new ObjectParameter("ended", ended) :
                new ObjectParameter("ended", typeof(System.DateTime));
    
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPR_Ganancia_Mes_Result>("SPR_Ganancia_Mes", consultory_uIdParameter, startParameter, endedParameter, id_userParameter);
        }
    
        public virtual ObjectResult<SPR_GetLastDataThisMonth_Result> SPR_GetLastDataThisMonth(Nullable<System.Guid> consultory_uId)
        {
            var consultory_uIdParameter = consultory_uId.HasValue ?
                new ObjectParameter("consultory_uId", consultory_uId) :
                new ObjectParameter("consultory_uId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPR_GetLastDataThisMonth_Result>("SPR_GetLastDataThisMonth", consultory_uIdParameter);
        }
    
        public virtual ObjectResult<SPR_Servicio_Cantidad_Result> SPR_Servicio_Cantidad(Nullable<System.Guid> consultory_uId, Nullable<System.DateTime> start, Nullable<System.DateTime> ended, Nullable<int> id_user)
        {
            var consultory_uIdParameter = consultory_uId.HasValue ?
                new ObjectParameter("consultory_uId", consultory_uId) :
                new ObjectParameter("consultory_uId", typeof(System.Guid));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endedParameter = ended.HasValue ?
                new ObjectParameter("ended", ended) :
                new ObjectParameter("ended", typeof(System.DateTime));
    
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPR_Servicio_Cantidad_Result>("SPR_Servicio_Cantidad", consultory_uIdParameter, startParameter, endedParameter, id_userParameter);
        }
    
        public virtual ObjectResult<SPR_TotalCYGanancia_Result> SPR_TotalCYGanancia(Nullable<System.Guid> consultory_uId, Nullable<System.DateTime> start, Nullable<System.DateTime> ended, Nullable<int> id_user)
        {
            var consultory_uIdParameter = consultory_uId.HasValue ?
                new ObjectParameter("consultory_uId", consultory_uId) :
                new ObjectParameter("consultory_uId", typeof(System.Guid));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endedParameter = ended.HasValue ?
                new ObjectParameter("ended", ended) :
                new ObjectParameter("ended", typeof(System.DateTime));
    
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPR_TotalCYGanancia_Result>("SPR_TotalCYGanancia", consultory_uIdParameter, startParameter, endedParameter, id_userParameter);
        }
    }
}
